### ISSUE TITLE
Hardcoded credentials available publicly

### ISSUE THREAD

**Issue by nc0fr** [BananeChocolat/Asuka#2]
Hi, I have found a [set of hardcoded credentials within an URL](https://github.com/BananeChocolat/Asuka/blob/d667f8462086544f3653d0e17df19d42ebd82db3/commands/randomplane.js#L19C34-L19C99) published here on GitHub.  I have therefore opened this issue to quickly inform you about this negligence in the hope of helping.

**Comment by BananeChocolat** [comment]
merci le sang
